services:
  app:
    image: mysociety/template_data_repo:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/template_data_repo
    volumes:
      - ./:/workspaces/template_data_repo/
      - /workspaces/template_data_repo/.venv
