#!/bin/bash
set -euo pipefail

if git remote get-url template >/dev/null 2>&1; then
    git remote set-url template https://github.com/mysociety/template_data_repo
else
    git remote add template https://github.com/mysociety/template_data_repo
fi
git fetch template
git merge template/main

git submodule sync --recursive
git submodule update --init --recursive
